### PR TITLE
Switch from JSHint/JSCS to ESLint

### PR DESCRIPTION
**Pull request by kadamwhite**
The main motivation of this change is an inexplicable error when running JSHint via Grunt:

```
Warning: Path must be a string. Received null
Use --force to continue.
```

JSS is effectively deprecated, so a migration to ESLint was likely. This is the straw that breaks the camel's back.

### CODE REVIEW

**Comment by sp90** [comment]
Just out of interest whats the benefit of using ESLint over JSHint and JSCS?

**Comment by kadamwhite** [comment]
the [jscs team has joined eslint](http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint); obviously the lack of future support doesn't mean we have to switch, but if we ever refactor this into ES modules or otherwise move beyond the current boundaries of current ES6 we'd want to shift. I'm a big supporter of JSHint but given the overlap between ESLint and JSHint, it felt like standardizing on one was more straightforward.

**Comment by sp90** [comment]
Thanks for the elboration

**Comment by kadamwhite** [comment]
@sp90 I'm open to alternative opinions, if you have any objection :) I think the issue's within grunt-contrib-jshint; test scripts that worked last week no longer work, so it's probably some nested NPM dependency of some sort, or something I did to upgrade my local environment that broke back-compat necessary to run one of those nested dependencies. Since I believe the JSHint command still works for me locally, and since this PR is largely motivated by a selfish desire to not be blocked by my build tools, the alternative would be to invoke jscs and jshint directly from npm rather than going through grunt, which would certainly reduce the number of moving parts. Given that eslint may not actually be capable of enforcing the whitespace rules we have as they are described in JSCS, that might be a preferable solution for the short term.

**Comment by kadamwhite** [comment]
Closed in favor of #172

**Pull request closed without merging**
